# INPUT SPLITS #######################################################################################

#To generate a neutral proxy set from a genome, you will need: the .fa file for the target genome (all chromosomes)
genome_fasta: "data/hg19.fa"

#The data folder should also contain .maf and .fa files for the reference & multi alignments for each chromosome target of interest. These files should be named what the chromosome targets are named,
# and should also be hard-masked (repeats are converted to Ns). These should be named e.g. "chr7.masked.fa" and "chr7.masked.maf"
maf_pattern: "data/{chrom}.masked.maf"
#if providing a MAF file, provide the reference sequence location here.
fa_pattern: "data/{chrom}.masked.fa"

#Provide the tree of the species in the MAF alignment:
tree_topology: "(rheMac3,(ponAbe2,(gorGor3,(panTro4,hg19))))"

#chrom_targets: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]
chrom_targets: ["chr1", "chr2", "chrX"]
